config/routes.rb
Rails.application.routes.draw do
  
  #get 'cards/index'
  #get 'cards/show'
  #get 'cards/new'
  #get 'cards/edit'
  resources :boards do
    resources :lists do
      resources :cards do
        member do
          get :delete
        end
      end

      member do
        get :delete
      end
    end
    member do
      get :delete
    end
  end
  
  #devise_for :users
  #root 'home#index'
  #devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html 
  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :confirmations => "users/confirmations",
    :invitations => "users/invitations"
  }

  devise_scope :user do
    authenticated :user do
      root 'boards#index', as: :root
    end
    unauthenticated do
      root "users/sessions#new", as: :unauthenticated_root
    end
  end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :cards, dependent: :destroy
  
  validates :name, :presence => true,
                         :length => {:maximum => 25},
                         :format => {:with => /[a-zA-Z]/}
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  
  before_action :set_list, only: %i[ show edit update delete destroy ]
  before_action :authenticate_user!
  before_action :get_board
  load_and_authorize_resource :board
  #load_and_authorize_resource :list, :through => :board 
  
  def index
    #@lists = List.where(board_id: @board.id)
    @lists = @board.lists.order("updated_at DESC")
  end

  def show
    @cards = @list.cards
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.board_id = @board.id
    
    if @list.save
      flash[:notice] = "List created successfully......"
      redirect_to board_lists_path(@board)
    else
      flash[:notice] = "Invalid List Name!!!"
      render('new')
    end

  end

  def edit
  end

  def update
    if @list.update(list_params)
      flash[:notice] = "List updated successfully......"
      redirect_to board_lists_path(@board)
    else
      flash[:notice] = "Invalid List Name!!!"
      render('edit')
    end
  end

  def destroy
    @list.destroy
    redirect_to board_lists_path
    flash[:notice] = "List '#{@list.name}' deleted successfully......"
  end

  private

    def set_list
      @list = List.find(params[:id])
    end
    
    def get_board
      @board = Board.find(params[:board_id])
    end
    
    def list_params
      params.required(:list).permit(:name)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%=error_messages_for(f.object)%>
<table summary="List for fields">
  <tr>
    <th>List Name</th>
    <td><%= f.text_area(:name)%></td>
  </tr>      
</table>

app/views/lists/edit.html.erb
<div class="List Update">
  <h1>Update List</h1>
  <%= form_for([@board, @list]) do |f| %>
    <%= render(:partial => 'form',:locals => {:f => f}) %>
    <div class="form-buttons">
      <%= f.submit("Update List")%>
    </div>
  <%end%>
  <%= link_to 'Back', board_lists_path(@board) %>
</div>

app/views/lists/index.html.erb
<h1>All Lists</h1>
<% if @lists.empty? %>
  <%= "No List is Added Yet!!!" %>
<% else %>
  <h4>Board Name : <%= @lists.first.board.name %></h4>
  <table class="table table-striped table-dark table-hover">
    <thead>
      <tr>
        <th scope="col">List Name</th>
        <th scope="col">Show</th>
        <th scope="col">Edit</th>
        <th scope="col">Destroy</th>
      </tr>
    </thead>
    <tbody>
      <% @lists.each do |list| %>
        <tr>
          <td><%= list.name %></td>
          <td><%= link_to 'Show List Cards', board_list_cards_path(list.board_id, list) %></td>
          <td><%= link_to 'Edit', edit_board_list_path(list.board_id, list) %></td>
          <td><%= link_to 'Destroy', board_list_path(list.board_id, list), method: :delete %></td>
        </tr>  
      <% end %>
      
    </tbody>
  </table>
<% end %>
<%= link_to "Add List",new_board_list_path(:cutom => '123') , class:"nav-link" %>      

app/views/lists/new.html.erb
<div class="List new">
  <h1>Add new List</h1>
  <%= form_for([@board,@board.lists.build])do |f| %>
    <%= render(:partial => 'form',:locals => {:f => f}) %>
    <div class="form-buttons">
      <%= f.submit("Create List")%>
    </div>
  <%end%>
  <%= link_to 'Back', board_lists_path(@board) %>
</div>

app/views/lists/show.html.erb
<h1>Show List</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">List Name</th>
      <th scope="col">Created At</th>
      <th scope="col">Updated At</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td><%= @list.name %></td>
      <td><%= @list.created_at %></td>
      <td><%= @list.updated_at %></td>
    </tr>
  </tbody>
  <%= link_to 'Create Card',  new_board_list_card_path(@list.board_id,@list) %>
</table>