config/routes.rb
Rails.application.routes.draw do
  
  #get 'cards/index'
  #get 'cards/show'
  #get 'cards/new'
  #get 'cards/edit'
  resources :boards do
    resources :lists do
      resources :cards do
        member do
          get :delete
        end
      end

      member do
        get :delete
      end
    end
    member do
      get :delete
    end
  end
  
  #devise_for :users
  #root 'home#index'
  #devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html 
  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :confirmations => "users/confirmations",
    :invitations => "users/invitations"
  }

  devise_scope :user do
    authenticated :user do
      root 'boards#index', as: :root
    end
    unauthenticated do
      root "users/sessions#new", as: :unauthenticated_root
    end
  end
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :lists, dependent: :destroy
  
  validates :name, :presence => true,
                         :length => {:maximum => 25},
                         :format => {:with => /[a-zA-Z]/}
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  
  before_action :set_board, only: %i[ show edit update delete destroy ]
  before_action :authenticate_user!
  load_and_authorize_resource 
  
  def index
    @boards = current_user.boards.order("updated_at DESC")
  end

  def show
    @lists = @board.lists
  end

  def new
    @board = Board.new
  end

  def edit
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      flash[:notice] = "Board created successfully......"
      redirect_to("/boards")
    else
      render('new')
    end
  end

  def update
    
    if @board.update(board_params)
      flash[:notice] = "Board updated successfully......"
      redirect_to boards_path
    else
      render('edit')
    end
  
  end

  def delete
  end

  def destroy
    @board.destroy
    flash[:notice] = "Board '#{@board.name}' destroyed successfully......"
    redirect_to(boards_path)
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end
  
  def board_params
    params.required(:board).permit(:name,:user_id)
  end

end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary = "Board for fields">
  
  <tr>
    <th> Board Name </th>
    <td> <%= f.text_area(:name)%> </td>
  </tr> 
  
  <tr>
    <%= f.number_field :user_id, id: :board_user_id, value: current_user.id, type: :hidden %>
  </tr>      

</table>

app/views/boards/delete.html.erb
<div class = "board delete">
  
  <h1>Delete Board</h1>
  
  <%= form_for(@board, :url => board_path(@board), :method => 'delete')do |f| %>
    
    <p>Are you sure you want to delete this section </p>
    <p class = "reference-name"><%= @board.name%></p>


    <div class = "form-buttons">
      <%= f.submit("Delete Board") %>
    </div>
  <%end%>
</div>

app/views/boards/edit.html.erb
<div class = "board edit">
  
  <h1>Edit Board</h1>
  
  <%= form_for(@board, :url => board_path(@board), :method => 'patch') do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    
    <div class = "form-buttons">
      <%= f.submit("Update Board") %>
    </div>
  
  <% end %>
  
  <%= link_to 'Back', boards_path %>

</div>

app/views/boards/index.html.erb
<h1>All Boards</h1>

<table class = "table">
  
  <thead>    
    <tr>
      <th scope = "col"> Board Name </th>
      <th scope = "col"> Show </th>
      <th scope = "col"> Edit </th>
      <th scope = "col"> Destroy </th>
    
    </tr>
  </thead>
  
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.name %></td>
        <td><%= link_to 'Show Board Lists', board_lists_path(board) %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>        
        <td><%= link_to 'Destroy', delete_board_path(board) %></td>        
      </tr>
    <% end %>
    
    <tr> 
      <%= link_to "Add Board",new_board_path , class:"nav-link" %>      
    </tr>
    
  </tbody>
</table>

app/views/boards/new.html.erb
<div class = "board new">
  <h1> Add new Board </h1>
  
  <%= form_for(@board, :url => boards_path, :method => 'post') do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    
    <div class = "form-buttons">
      <%= f.submit("Create Board") %>
    </div>

  <%end%>
  
  <%= link_to 'Back', boards_path %>

</div>

app/views/boards/show.html.erb
<h1>Show Board</h1>

<table class = "table">
  
  <thead>
    <tr>
      <th scope = "col"> Board Name </th>
      <th scope = "col"> Created At </th>
      <th scope = "col"> Updated At </th>
    </tr>
  </thead>
  
  <tbody>
    <tr>
      <th scope = "row">1</th>
      <td><%= @board.name %></td>
      <td><%= @board.created_at %></td>
      <td><%= @board.updated_at %></td>
    </tr>
  </tbody>
  
  <%= link_to 'Create List',  new_board_list_path(@board) %>

</table>