config/routes.rb
Rails.application.routes.draw do
  
  #get 'cards/index'
  #get 'cards/show'
  #get 'cards/new'
  #get 'cards/edit'
  resources :boards do
    resources :lists do
      resources :cards do
        member do
          get :delete
        end
      end

      member do
        get :delete
      end
    end
    member do
      get :delete
    end
  end
  
  #devise_for :users
  #root 'home#index'
  #devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html 
  devise_for :users, :controllers => {
    :registrations => "users/registrations",
    :sessions => "users/sessions",
    :passwords => "users/passwords",
    :confirmations => "users/confirmations",
    :invitations => "users/invitations"
  }

  devise_scope :user do
    authenticated :user do
      root 'boards#index', as: :root
    end
    unauthenticated do
      root "users/sessions#new", as: :unauthenticated_root
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :list
  
  validates :name, :status, :presence => true,
                         :length => {:maximum => 25},
                         :format => {:with => /[a-zA-Z]/}
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  
  before_action :set_card, only: %i[ show edit update delete destroy ]
  before_action :authenticate_user!
  before_action :get_list
  before_action :get_board
  load_and_authorize_resource :board
  
  def index
    #@cards = Card.where(list_id: @list.id)
    @cards = @list.cards.order("updated_at DESC")
  end

  def show
        
  end

  def new
    #@board=@list.board
    #@board = Board.find(params[:board_id])
    @card = Card.new
  end

  def create
    #@board = Board.find(params[:board_id])
    #@board=@list.board
    @card = Card.new(card_params)
    @card.list_id = @list.id
    
    if @card.save      
      flash[:notice] = "Card created successfully......"
      redirect_to board_list_cards_path(@card.list.board, @card.list)
    else
      
      flash[:notice] = "Invalid Card Name!!!"
      render('new')      
    end
  
  end

  def edit
    #@board=@list.board
  end

  def update
    
    if @card.update(card_params)    
      flash[:notice] = "Card updated successfully......"
      redirect_to board_list_cards_path(@card)
    else
      flash[:notice] = "Invalid Card Name!!!"
      render('edit')
    end
  
  end

  def destroy  
    @card.destroy
    redirect_to board_list_cards_path
    flash[:notice] = "Card '#{@card.name}' deleted successfully......"
  end
  
  private
  
    def set_card
      @card = Card.find(params[:id])
    end
    
    def get_list
      @list = List.find(params[:list_id])
    end
    
    def get_board
      @board = @list.board
    end
    
    def card_params
      params.required(:card).permit(:name,:status)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary = "Cards for fields">
  
  <tr>
    <th>Card Name</th>
    <td><%= f.text_area(:name) %></td>
  </tr>
  
  <tr>
    <th>Card Status</th>
    <td><%= f.text_area(:status) %></td>
  </tr>      

</table>

app/views/cards/edit.html.erb
<div class = "Card Update">
  
  <h1>Update Card</h1>
  
  <%= form_for([@board, @list, @card]) do |f| %>
    <%= render(:partial => 'form', :locals => {:f => f}) %>
    
    <div class = "form-buttons">
      <%= f.submit("Update Card")%>
    </div>
  
  <%end%>
  
  <%= link_to 'Back', board_list_cards_path(@list) %>

</div>

app/views/cards/index.html.erb
<h1>All Cards</h1>

<% if @cards.empty? %>
  <%= "No Card is Added Yet!!!" %>
<% else %>
  
  <h4>List Name : <%= @cards.first.list.name %></h4>
  
  <table class = "table table-secondary">
    
    <thead>
      <tr>
        <th scope = "col">Card Name</th>
        <th scope = "col">Card Status</th>
        <th scope = "col">Show</th>
        <th scope = "col">Edit</th>
        <th scope = "col">Destroy</th>
      </tr>
    </thead>
    
    <tbody>
      <% @cards.each do |card| %>
        <tr>
          <td><%= card.name %></td>
          <td><%= card.status %></td>
          <td><%= link_to 'Show', board_list_card_path(card.list.board_id, card.list_id, card) %></td>
          <td><%= link_to 'Edit', edit_board_list_card_path(card.list.board_id, card.list_id, card) %></td>
          <td><%= link_to 'Destroy', board_list_card_path(card.list.board_id, card.list_id, card), method: :delete %></td>
        </tr>  
      <% end %>
    </tbody>
  
  </table>
<% end %>

<%= link_to "Add Card",new_board_list_card_path , class:"nav-link" %>

app/views/cards/new.html.erb
<div class = "Card new">
  <h1>Add new Card</h1>
  <%= form_for([@board, @list, @list.cards.build]) do |f| %>
    <%= render(:partial => 'form',:locals => {:f => f}) %>
    
    <div class = "form-buttons">
      <%= f.submit("Create Card")%>
    </div>
  
  <%end%>
  
  <%= link_to 'Back', board_list_cards_path(@list) %>

</div>

app/views/cards/show.html.erb
<h1>Show Card</h1>

<table class = "table">
  <thead>
    <tr>
      <th scope = "col">Card Name</th>
      <th scope = "col">Card Status</th>
      <th scope = "col">Created At</th>
      <th scope = "col">Updated At</th>
    </tr>
  </thead>
  
  <tbody>
    <tr>
      <td><%= @card.name %></td>
      <td><%= @card.status %></td>
      <td><%= @card.created_at %></td>
      <td><%= @card.updated_at %></td>
    </tr>
  </tbody>
  
  <%= link_to 'Back', board_list_cards_path %>

</table>